project_name: flush
before:
  hooks:
    - go mod download
builds:
  - binary: plugin.so
    main: plugin.go
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
      - -buildmode=plugin
    goos:
      - linux
    goarch:
      - amd64
      - 386
    ldflags:
      - -s -w
archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}_{{ .Binary }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
