name: Release
on:
  push:
    tags:
      - "*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: plugin
      - uses: actions/checkout@v2
        with:
          repository: riposo/riposo
          path: riposo
          token: ${{ secrets.PAT }}
          ref: ${{ github.ref }}
      - name: Install packages
        run: |
          sudo apt-get install -y --no-install-recommends gcc-multilib g++-multilib
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
          workdir: plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
