name: Release
on:
  push:
    tags:
      - "*"
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      version-without-v: ${{ steps.get_version.outputs.version-without-v }}
    steps:
      - name: Extract Version
        id: get_version
        uses: battila7/get-version-action@v2
  release:
    runs-on: ubuntu-latest
    needs: init
    container:
      image: ghcr.io/riposo/build-env:${{ needs.init.outputs.version-without-v }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare
        run: |
          apt-get update
          apt-get install -y --no-install-recommends gcc-multilib g++-multilib
      - name: Fetch goreleaser
        uses: engineerd/configurator@v0.0.6
        with:
          name: goreleaser
          url: https://github.com/goreleaser/goreleaser/releases/download/v0.160.0/goreleaser_Linux_x86_64.tar.gz
          pathInArchive: goreleaser
      - name: Run GoReleaser
        run: |
          workspace=$(pwd); cd /; ln -sfn $workspace plugin
          cd /plugin
          goreleaser release --rm-dist
        env:
          GORELEASER_CURRENT_TAG: v${{ needs.init.outputs.version-without-v }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
